### PR TITLE
Changed Token and ServerUrl to Layout for easier configuration. (DEV …

### PR DESCRIPTION
**Pull request by Bjego**
…and PROD Splunk)

Hey @AlanBarber , I changed the Token and the ServerUrl to Layouts. Now we can use Appsettings.json to configure these values.

With best regards,
Bjego

### CODE REVIEW

**Comment by Bjego** [comment]
Hey @AlanBarber any news on this PR? Can you give me an update please?

**Comment by Bjego** [comment]
@AlanBarber i changed the spacing bach to 4 spaces

**Comment by Bjego** [comment]
@AlanBarber any news on this feature?

**Comment by AlanBarber** [comment]
going to close this out due to other pull request with changes.

**Pull request closed without merging**
