### PR TITLE
Introduced IgnoreSslErrors property

### PR DESCRIPTION
**Pull request by snakefoot**

### CODE REVIEW

**Comment by snakefoot** [comment]
@initech-asynchrony @bruceharrison1984 Since you have shown to compile and make local changes, then you try to see if this PR ensures error-logging is working and that ssl-certificate-errors can be ignored.

**Comment by snakefoot** [comment]
Since IgnoreSslErrors is a very special for you only. Then one might consider not having the extra dependency on System.Net.Http.WebRequest.

Instead just provide the ability to assign a delegate `Func<HttpMessageHandler>`. Could be a static-member. When assigned it will create a HttpClient with the returned HttpMessageHandler.

Then the custom code for IgnoreSslErrors could be moved into your solution, and not clutter `NLog.Targets.Splunk` (Removing `IgnoreSslErrors` competely).

**Comment by bruceharrison1984** [comment]
This PR fixes our problems, but I would like to re-iterate that ignoreSSL has a number of valid use cases beyond my particular situation.

**Comment by snakefoot** [comment]
@AlanBarber I guess it is your decision whether IgnoreSslErrors should be official part of the API, or if it should be custom extensions.

I guess if we accepted `Func<HttpRequestMessage, X509Certificate2, X509Chain, SslPolicyErrors, bool>` as parameter. Then it would be possible for NetCoreApps to provide a direct reference to the static HttpClientHandler.DangerousAcceptAnyServerCertificateValidator, thus this will work:

https://github.com/dotnet/corefx/blob/fe63206856998c223adb0240a1e57201b6cfd467/src/System.Net.Http/src/System/Net/Http/CurlHandler/CurlHandler.EasyRequest.cs#L773

**Comment by AlanBarber** [comment]
I'm fine adding an IgnoreSslErrors option to the API... I actually originally implemented a version of it for my  log4net provider but when I converted to .NET Standard I had to remove it because there was no support at the time.

**Comment by snakefoot** [comment]
The always ignoreSslErrors = true is just me opening for the ability to have other future  reasons to call BuildHttpMessageHandler . Ex maybe want to restrict to only use Tsl12



Sent from my Samsung device


-------- Original message --------

**Comment by AlanBarber** [comment]
@snakefoot Gotcha sounds good... i'm going to get an RC pushed up to github now

**Pull request merged**
