### PR TITLE
Changed ServerUrl and Token into NLog Layout and added Index + Source + SourceType

### LINKED ISSUE #31: Hard coded Source Type
Add source type as a configurable setting per request from https://github.com/AlanBarber/Microsoft.Extensions.Logging.Splunk/issues/1

### PR DESCRIPTION
**Pull request by snakefoot**
Also as NLog Layout. See also #37 and resolves #31

csproj-files modified because I'm now using VS2019 and it doesn't include net462 by default.

### CODE REVIEW

**Comment by snakefoot** [comment]
@AlanBarber This is a breaking interface change. But has the nice side-effect that one can use NLog-Layout logic.

**Comment by snakefoot** [comment]
Not as fancy as #30, but has less memory allocations.

**Comment by AlanBarber** [comment]
Looks good, I'll get a new build published out shortly.

**Comment by snakefoot** [comment]
@AlanBarber Thank you for the merge. Any chance for an updated nuget-package?

**Pull request merged**
